runtime: nodejs20
service: call-automation-frontend

env_variables:
  NODE_ENV: production

automatic_scaling:
  target_cpu_utilization: 0.8
  min_instances: 0
  max_instances: 10
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: 10s

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

entrypoint: npm start

handlers:
  # Serve static files from public directory
  - url: /(.*\.(png|jpg|jpeg|gif|svg|ico|txt|json|webp))$
    static_files: public/\1
    upload: public/.*\.(png|jpg|jpeg|gif|svg|ico|txt|json|webp)
    secure: always
    expiration: "1h"

  # All routes handled by Next.js server
  - url: /.*
    script: auto
    secure: always
